name: Add project application to project board

on:
  issues:
    types: [labeled]

jobs:
  Add_New_Project_Application_Issue_To_Project_Board:    
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/actions-add-new-issue-to-column@7a9ee8bfa125bf97c2fcfbac20ae8f82657f83ba
      if: contains(github.event.issue.labels.*.name, 'project application')
      with:
        action-token: "${{ secrets.ACCESS_TOKEN }}"
        project-url: "https://github.com/dotnet-foundation/projects/projects/1"
        column-name: "New Project Application"
