name: Code Signing Certificate Request
description: Request code signing certificate for an existing .NET Foundation project
title: "[Code Signing Certificate]: <project name>"
labels: ["project support", "triage"]
assignees:
  - ChrisSfanos
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the information below to request a code signing certificate for your existing .NET Foundation project.

        You will need a LastPass account for receiving the credentials. If you'd prefer to provide the email address via email, please email project-support@dotnetfoundation.org with it.

        You can ping on discord for status, but GitHub issues is the primary way to request support to allow for tracking
        and involving the project support team.
  - type: input
    id: project-name
    attributes:
      label: Project Name
      description: What is the name of the project
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: input
    id: lastpass-email
    attributes:
      label: LastPass Email
      description: What email should be used for LastPass
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: checkboxes
    id: onboarding
    attributes:
      label: Onboarding Checklist
      description: Certificate onboarding checklist - Used by Staff
      options:
        - label: Register trade name @ChrisSfanos
        - label: Create configuration in Code Signing Service
        - label: Create organization with DigiCert
        - label: Request certificate from DigiCert
        - label: Received certificate and finalize sign service configuration
        - label: Provide credentials in shared folder in LastPass

